### ISSUE TITLE
Issues with opening trunk

### ISSUE THREAD

**Issue by Blazzer10200** [darktrovx/interact#12]
When you try to access trunk it just says undefind and will not open inventory I'm on the latest version

![image](https://github.com/darktrovx/interact/assets/121213450/21c0ef3c-d211-4ec8-a485-a7a62e9ecad0)

**Comment by snalye** [comment]
If you haven't adjusted that interact, it may be the default one

https://github.com/darktrovx/interact/blob/58df296b9e928eec2c49d4414855814386398b29/client/defaults.lua#L7-L34

**Comment by Blazzer10200** [comment]
I have tried that @snalye I'm on the most updated version of this script and ox_inventory still It says undefind

**Comment by g-ionas** [comment]
Change "title" to "description" in lines 18 and 22 (or generally in any return lib.notify in the interact script). Worked for me.

**Comment by mafewtm** [comment]
Tested and works as intended. No issue present from what I can see.
