### ISSUE TITLE
Interact options

### ISSUE THREAD

**Issue by Billtorch** [darktrovx/interact#15]
Before the update when you had only one option the circle select was not shown 
![screenshot3](https://github.com/darktrovx/interact/assets/64261770/c9f6d812-1c80-4f36-bd5c-2cd985365777) example!
After the update even if you only have one option the circle shows all the time 
![Screenshot_2](https://github.com/darktrovx/interact/assets/64261770/c55b966f-11d9-4d49-adb0-91c0f507050e)

**Comment by FjamZoo** [comment]
This has been fixed
