### ISSUE TITLE
[Suggestion] Item requirments

### ISSUE THREAD

**Issue by GeoGaming** [darktrovx/interact#18]
Hi guys, love the script.

qb-target often has a "required item" option to allow the interaction. Its a really easy way to restrict the interaction based on an item. I am writing some code to handle this outside the interaction but thought it might be good if you guys integrated it into the script.

Cheers,

**Comment by FjamZoo** [comment]
We wont be including items as that would overcomplicate the bridge too much having to add compatability for 30-40 different shitty qb-inventory reskins.
