### ISSUE TITLE
In prop can't load 'E', Only point

### ISSUE THREAD

**Issue by abesarrr** [darktrovx/interact#25]
![image](https://github.com/darktrovx/interact/assets/29142147/a1ef2997-a933-4014-b710-2eb7dc728898)

![image](https://github.com/darktrovx/interact/assets/29142147/ac29c0fd-46d6-40eb-be0c-ffcb9cbf6298)

**Comment by FjamZoo** [comment]
This is becuase you are not looking at the prop.

use ignoreLos
