### ISSUE TITLE
The pin blocks interaction

### ISSUE THREAD

**Issue by abesarrr** [darktrovx/interact#3]
![image](https://github.com/darktrovx/interact/assets/29142147/b25e587c-ddf7-4aff-9f80-2f0a84f047c0)
how to remove this pin when approaching the pin?

**Comment by Nathan-FiveM** [comment]
You are creating two interact points at the same location, create one with multiple fields in options

**Comment by FjamZoo** [comment]
This is what Nathan said above this is not anything in the resource that could recreate that behavior
