### ISSUE TITLE
[SCRIPT ERROR] entitis.lua135: (waited 10005.0ms)

### ISSUE THREAD

**Issue by LYRYCAL** [darktrovx/interact#35]
This issue always show up on the F8 when after every player joining the server.

![Screenshot_23](https://github.com/user-attachments/assets/6efaf698-81f8-45b7-9d51-40627a20b6fb)

**Comment by mafewtm** [comment]
When a player joins, it retrieves the player's ID, waits for their ped (game entity) to be loaded and then stores the ped and player information in a table. This error is caused by the function not getting the player ped within the allotted timeframe. That timeframe being 10000ms or 10 seconds.

**Comment by mafewtm** [comment]
Increase it if need be.
