### ISSUE TITLE
[Suggestion] Job's

### ISSUE THREAD

**Issue by Obtaizen** [darktrovx/interact#4]
Make it so if your a certain job only that job can see the interaction

**Comment by FjamZoo** [comment]
This was added inside the refactor branch.

Might be a couple of days before the branch is ready to be fully tested

**Comment by Obtaizen** [comment]
Thanks for getting back to me :)

**Comment by FjamZoo** [comment]
> Thanks for getting back to me :)

Thank you for your suggestion this has been merged into the main repo :)
