### ISSUE TITLE
canInteract

### ISSUE THREAD

**Issue by Nathan-FiveM** [darktrovx/interact#6]
Using the can interact function removes the option visually however you can still scroll and click the option anyway

**Comment by FjamZoo** [comment]
Caninteract is meant to hide the option completely.

If you want an option that is still there that they can press on but wont fire an event? then just add checks into your events

**Comment by FjamZoo** [comment]
FYI this has been fixed inside the refactor branch.

It might be a couple of days untill testing and merge.

**Comment by Nathan-FiveM** [comment]
Been testing the refactor branch, so far so good, haven't ran into any other "Major" issues as of yet
