### ISSUE TITLE
[Suggestion] Disable point or options per interaction point while in vehicle

### ISSUE THREAD

**Issue by jnccloud** [darktrovx/interact#8]
In addition to globally disallowing/allowing options, I suggest implementing a new parameter that means `enableInVehicle`. So, if you have the global `onVehicle = true` you could manually set some points to be allowed, such as mechanic repair benches.  I know this can be done with canInteract, but for ease of use a parameter would be ideal.

**Comment by FjamZoo** [comment]
I mean no matter the solution we will come up with it will run the same as you just using canInteract and disabling the dissapearing of points when inside vehicles
